"""
PDF Export Utility
------------------
Generates professional PDF question papers using fpdf2.
Supports Unicode math symbols for basic mathematical notation.
"""

from fpdf import FPDF
from datetime import datetime
import os
import tempfile


class QuestionPaperPDF(FPDF):
    """Custom PDF class for generating formatted question papers."""

    def __init__(self, paper_data, questions, subject_name, faculty_name):
        """
        Initialize the PDF generator.

        Args:
            paper_data (dict): Paper metadata (total_marks, exam_type, exam_date).
            questions (list[dict]): List of questions with marks and metadata.
            subject_name (str): Subject name.
            faculty_name (str): Faculty who generated the paper.
        """
        super().__init__()
        self.paper_data = paper_data
        self.questions = questions
        self.subject_name = subject_name
        self.faculty_name = faculty_name

        # Use built-in fonts that support basic characters
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        """Draw the paper header with university and exam details."""
        # University name
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 8, 'University of Technology', ln=True, align='C')

        # Department
        self.set_font('Helvetica', '', 11)
        self.cell(0, 6, 'Department of Computer Science & Engineering', ln=True, align='C')

        # Divider line
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.8)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

        # Exam type
        exam_type = self.paper_data.get('exam_type', 'Internal Assessment')
        self.set_font('Helvetica', 'B', 13)
        self.cell(0, 7, exam_type, ln=True, align='C')
        self.ln(2)

        # Subject and details row
        self.set_font('Helvetica', '', 10)
        exam_date = self.paper_data.get('exam_date', datetime.now().strftime('%Y-%m-%d'))
        if hasattr(exam_date, 'strftime'):
            exam_date = exam_date.strftime('%d-%m-%Y')

        total_marks = self.paper_data.get('total_marks', 0)

        # Left side: Subject
        self.cell(95, 6, f'Subject: {self.subject_name}', ln=False, align='L')
        # Right side: Date
        self.cell(95, 6, f'Date: {exam_date}', ln=True, align='R')

        # Second row
        self.cell(95, 6, f'Max Marks: {total_marks}', ln=False, align='L')

        # Calculate duration based on marks
        duration_map = {20: '1 Hour', 30: '1.5 Hours', 50: '2 Hours'}
        duration = duration_map.get(total_marks, '1.5 Hours')
        self.cell(95, 6, f'Duration: {duration}', ln=True, align='R')

        # Divider
        self.set_line_width(0.4)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(5)

        # Instructions
        self.set_font('Helvetica', 'B', 9)
        self.cell(0, 5, 'Instructions:', ln=True)
        self.set_font('Helvetica', '', 9)
        self.cell(0, 5, '1. Answer all questions.', ln=True)
        self.cell(0, 5, '2. Marks for each question are indicated on the right.', ln=True)
        self.cell(0, 5, '3. Draw neat diagrams wherever necessary.', ln=True)
        self.ln(4)

        # Another divider
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        """Draw page footer with page number."""
        self.set_y(-20)
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

        self.set_font('Helvetica', 'I', 8)
        self.cell(95, 5, f'Generated by SmartQGen | {self.faculty_name}', align='L')
        self.cell(95, 5, f'Page {self.page_no()}/{{nb}}', align='R')

    def generate(self):
        """Generate the complete question paper PDF."""
        self.alias_nb_pages()
        self.add_page()

        current_module = None
        q_num = 1

        for question in self.questions:
            # Module header
            module = question.get('module_number', 1)
            if module != current_module:
                current_module = module
                self.ln(3)
                self.set_font('Helvetica', 'B', 11)
                self.set_fill_color(240, 244, 248)
                self.cell(0, 7, f'  Module {module}', ln=True, fill=True)
                self.ln(2)

            # Question
            marks = question.get('marks', 0)
            text = question.get('question_text', '')

            # Sanitize text - replace unsupported characters
            text = self._sanitize_text(text)

            # Question number and text
            self.set_font('Helvetica', 'B', 10)
            q_label = f'Q{q_num}. '

            # Calculate text width for multi-line
            self.set_font('Helvetica', '', 10)
            marks_label = f'[{marks} Marks]'
            marks_width = self.get_string_width(marks_label) + 4

            # Print question number in bold
            self.set_font('Helvetica', 'B', 10)
            self.cell(10, 6, q_label, ln=False)

            # Print question text
            self.set_font('Helvetica', '', 10)
            # Available width for question text (leave room for marks)
            text_width = 190 - 10 - marks_width

            # Use multi_cell for long questions
            x_before = self.get_x()
            y_before = self.get_y()

            self.multi_cell(text_width, 6, text)

            y_after = self.get_y()

            # Print marks on the right side at the first line
            self.set_xy(190 - marks_width, y_before)
            self.set_font('Helvetica', 'B', 10)
            self.set_text_color(0, 51, 102)
            self.cell(marks_width, 6, marks_label, align='R')
            self.set_text_color(0, 0, 0)

            # Move to after the question text
            self.set_y(max(y_after, y_before + 6))
            self.ln(2)

            q_num += 1

        # CO/PO Mapping Table
        self._add_mapping_table()

        return self

    def _sanitize_text(self, text):
        """Replace characters that may not be supported by the font."""
        # Replace common unicode with ASCII equivalents
        replacements = {
            '\u2013': '-',   # en dash
            '\u2014': '--',  # em dash
            '\u2018': "'",   # left single quote
            '\u2019': "'",   # right single quote
            '\u201c': '"',   # left double quote
            '\u201d': '"',   # right double quote
            '\u2026': '...', # ellipsis
            '\u2022': '*',   # bullet
            '\u00d7': 'x',   # multiplication sign
            '\u00f7': '/',   # division sign
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        return text

    def _add_mapping_table(self):
        """Add CO/PO mapping table at the end of the paper."""
        self.ln(8)
        self.set_font('Helvetica', 'B', 10)
        self.cell(0, 7, 'CO-PO Mapping:', ln=True)
        self.ln(2)

        # Table header
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(0, 51, 102)
        self.set_text_color(255, 255, 255)

        col_widths = [15, 85, 20, 25, 25, 20]
        headers = ['Q.No', 'Question', 'Marks', 'CO', 'PO', 'Module']

        for i, header in enumerate(headers):
            self.cell(col_widths[i], 7, header, border=1, fill=True, align='C')
        self.ln()

        # Table rows
        self.set_text_color(0, 0, 0)
        self.set_font('Helvetica', '', 8)

        for i, q in enumerate(self.questions, 1):
            # Alternate row colors
            if i % 2 == 0:
                self.set_fill_color(245, 247, 250)
                fill = True
            else:
                fill = False

            # Truncate question text for table
            q_text = q.get('question_text', '')[:50]
            if len(q.get('question_text', '')) > 50:
                q_text += '...'

            q_text = self._sanitize_text(q_text)

            self.cell(col_widths[0], 6, str(i), border=1, fill=fill, align='C')
            self.cell(col_widths[1], 6, q_text, border=1, fill=fill)
            self.cell(col_widths[2], 6, str(q.get('marks', '')), border=1, fill=fill, align='C')
            self.cell(col_widths[3], 6, q.get('co_mapping', ''), border=1, fill=fill, align='C')
            self.cell(col_widths[4], 6, q.get('po_mapping', ''), border=1, fill=fill, align='C')
            self.cell(col_widths[5], 6, str(q.get('module_number', '')), border=1, fill=fill, align='C')
            self.ln()

        # Total marks row
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(0, 51, 102)
        self.set_text_color(255, 255, 255)
        self.cell(col_widths[0], 7, '', border=1, fill=True)
        self.cell(col_widths[1], 7, 'Total', border=1, fill=True, align='R')
        total = sum(q.get('marks', 0) for q in self.questions)
        self.cell(col_widths[2], 7, str(total), border=1, fill=True, align='C')
        self.cell(col_widths[3] + col_widths[4] + col_widths[5], 7, '', border=1, fill=True)
        self.set_text_color(0, 0, 0)


def generate_pdf(paper_data, questions, subject_name, faculty_name):
    """
    Generate a PDF question paper and return the file path.

    Args:
        paper_data (dict): Paper metadata.
        questions (list[dict]): Questions with their details.
        subject_name (str): Name of the subject.
        faculty_name (str): Name of the faculty.

    Returns:
        str: Path to the generated PDF file.
    """
    pdf = QuestionPaperPDF(paper_data, questions, subject_name, faculty_name)
    pdf.generate()

    # Create a temporary file for the PDF
    filename = f"SmartQGen_{subject_name.replace(' ', '_')}_{paper_data.get('exam_date', 'paper')}.pdf"
    # Use a directory within the app for generated PDFs
    output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'generated_papers')
    os.makedirs(output_dir, exist_ok=True)

    filepath = os.path.join(output_dir, filename)
    pdf.output(filepath)

    return filepath
